import { parseFormRows } from "./parse-form";

const MOCK_SHEET: unknown[][] = [
  [
    "Your Full Name (first & surname)",
    "Full name of spouse",
    "How many family members (including yourself and your spouse) are travelling altogether?",
    "Shuttle Drop Off (inbound)",
    "INBOUND: Do you require a Shuttle pick-up on Tuesday 22 or Wednesday 23 July?",
    "What date do you arrive?",
    "What airport do you arrive at?",
    "Name of Airline",
    "Flight code and number (ie. BA222)",
    "Expected UK Flight Arrival time. (Please use 24hr clock).",
    "After Shout Conference, do you require a Shuttle back to the Airport on Saturday 26 July?",
    "Shuttle Pick Up (outbound)",
    "What airport are you departing from?",
    "Name of Airline 2",
    "Flight code and number (ie. BA222) 2",
    "UK Flight Departure time. (Please use 24hr clock).",
    "If you require baby or child booster seat(s)...[Baby Seat (0-12 months)]",
    "If you require baby or child booster seat(s)...[Toddler Seat (12 months - 2/3 years)]",
    "If you require baby or child booster seat(s)...[Child Seat (3-5 years)]",
    "If you require baby or child booster seat(s)...[Booster Seat (5+ years)]",
    "Your mobile number (UK or international)",
    "Email",
  ],
  [
    "Alex Example",
    "",
    "2",
    "Travelodge Guildford",
    "Tuesday: Heathrow",
    "Tuesday 22 July",
    "Heathrow Terminal 2",
    "BA",
    "BA123",
    0.625,
    "Yes, Shuttle to Heathrow",
    "Harbour Hotel Guildford",
    "Heathrow Terminal 2",
    "BA",
    "BA456",
    0.7916666666666666,
    "0",
    "1",
    "0",
    "0",
    "+447700900111",
    "alex@example.com",
  ],
  [
    "Sam Sample",
    "Pat Sample",
    "",
    "Mandolay Hotel",
    "Wednesday: Heathrow",
    "Wednesday 23 July",
    "Heathrow Terminal 5",
    "VS",
    "VS4",
    0.65625,
    "Yes, Shuttle to Heathrow",
    "Mandolay Hotel",
    "Heathrow Terminal 5",
    "VS",
    "VS99",
    0.8125,
    "0",
    "0",
    "0",
    "0",
    "+447700900222",
    "sam@example.com",
  ],
  [
    "Big Family",
    "",
    "8",
    "G-Live / Guildford Station",
    "Tuesday pick-up · Heathrow",
    "Tuesday 22 July",
    "Heathrow Terminal 3",
    "EI",
    "EI123",
    0.6354166666666666,
    "No",
    "",
    "",
    "",
    "",
    "",
    "0",
    "0",
    "0",
    "0",
    "+447700900333",
    "big@example.com",
  ],
  [
    "Gate Wick",
    "",
    "1",
    "Harbour Hotel Guildford",
    "Tuesday: Heathrow",
    "Tuesday 22 July",
    "Gatwick North",
    "U2",
    "U2 111",
    0.6458333333333334,
    "No",
    "",
    "",
    "",
    "",
    "",
    "0",
    "0",
    "0",
    "0",
    "+447700900444",
    "gate@example.com",
  ],
  [
    "Dup Tester",
    "",
    "1",
    "Unknown Hotel Nowhere",
    "Tuesday: Heathrow",
    "Tuesday 22 July",
    "Heathrow Terminal 2",
    "BA",
    "BA777",
    0.65,
    "No",
    "",
    "",
    "",
    "",
    "",
    "1",
    "0",
    "0",
    "0",
    "+447700900555",
    "dup@example.com",
  ],
  [
    "Dup Tester Two",
    "",
    "1",
    "Travelodge Guildford",
    "No",
    "Tuesday 22 July",
    "Heathrow Terminal 2",
    "BA",
    "BA888",
    0.66,
    "No",
    "",
    "",
    "",
    "",
    "",
    "0",
    "0",
    "0",
    "0",
    "+447700900666",
    "dup@example.com",
  ],
];

export function getMockParseResult() {
  return parseFormRows(MOCK_SHEET);
}
